//looping infinite
// while (true) {
//     console.log('alwi');
// }

//program while
// var nama = prompt('Input Your Name');
// var coba = confirm('nama Anda :' + nama);
// while (coba) {
//     console.log('Hello' + nama);
//     coba = confirm('lagi?');
// }

//program while1

// var n = parseInt(prompt('Input nilai awal'));
// var m = parseInt(prompt('Input nilai akhir'));
// while (n <= m) {
//     console.log('Hello World ' + n + ' x');
//     n++;
// }

//Lt angkot

var n = 1;
var m = parseInt(prompt('Input Jumlah Angkot'))
while (n <= m) {
    console.log('Angkot no ' + n + ' Beroperasi dengan baik ')
    n++
}
